
export const ALIMENTOS_DB=[
{id:1,nombre:'Pollo pechuga 100g',cal:165,prot:31,carb:0,grasa:3.6,emoji:'🍗',cat:'Proteína'},
{id:2,nombre:'Arroz blanco 100g',cal:130,prot:2.4,carb:28,grasa:0.3,emoji:'🍚',cat:'Carbohidrato'},
{id:3,nombre:'Huevo entero',cal:68,prot:5.5,carb:0.5,grasa:4.7,emoji:'🥚',cat:'Proteína'},
{id:4,nombre:'Avena 50g',cal:194,prot:8,carb:33,grasa:3.4,emoji:'🥣',cat:'Carbohidrato'},
{id:5,nombre:'Atún en agua 100g',cal:144,prot:30,carb:0,grasa:1,emoji:'🐟',cat:'Proteína'},
{id:6,nombre:'Plátano mediano',cal:89,prot:1.1,carb:23,grasa:0.3,emoji:'🍌',cat:'Fruta'},
{id:7,nombre:'Brócoli 100g',cal:34,prot:2.8,carb:7,grasa:0.4,emoji:'🥦',cat:'Verdura'},
{id:8,nombre:'Leche entera 250ml',cal:150,prot:8,carb:12,grasa:8,emoji:'🥛',cat:'Lácteo'},
{id:9,nombre:'Whey proteína 1 scoop',cal:120,prot:24,carb:3,grasa:1,emoji:'💪',cat:'Suplemento'},
{id:10,nombre:'Aguacate 100g',cal:160,prot:2,carb:9,grasa:15,emoji:'🥑',cat:'Grasa saludable'},
{id:11,nombre:'Salmón 100g',cal:208,prot:20,carb:0,grasa:13,emoji:'🐟',cat:'Proteína'},
{id:12,nombre:'Papa cocida 100g',cal:77,prot:2,carb:17,grasa:0.1,emoji:'🥔',cat:'Carbohidrato'},
{id:13,nombre:'Carne res magra 100g',cal:250,prot:26,carb:0,grasa:15,emoji:'🥩',cat:'Proteína'},
{id:14,nombre:'Yogurt griego 150g',cal:88,prot:9,carb:5,grasa:0.7,emoji:'🍶',cat:'Lácteo'},
{id:15,nombre:'Manzana mediana',cal:52,prot:0.3,carb:14,grasa:0.2,emoji:'🍎',cat:'Fruta'},
{id:16,nombre:'Almendras 30g',cal:174,prot:6,carb:6,grasa:15,emoji:'🥜',cat:'Grasa saludable'},
{id:17,nombre:'Pan integral 1 rebanada',cal:79,prot:3,carb:13,grasa:1,emoji:'🍞',cat:'Carbohidrato'},
{id:18,nombre:'Queso panela 50g',cal:130,prot:10,carb:2,grasa:9,emoji:'🧀',cat:'Proteína'},
{id:19,nombre:'Frijoles cocidos 100g',cal:76,prot:5,carb:13,grasa:0.5,emoji:'🫘',cat:'Carbohidrato'},
{id:20,nombre:'Tortilla maíz 1 pza',cal:70,prot:1.5,carb:14,grasa:1,emoji:'🌮',cat:'Carbohidrato'},
{id:21,nombre:'Pechuga pavo 100g',cal:135,prot:29,carb:0,grasa:1,emoji:'🦃',cat:'Proteína'},
{id:22,nombre:'Pasta cocida 100g',cal:158,prot:5.8,carb:30,grasa:0.9,emoji:'🍝',cat:'Carbohidrato'},
{id:23,nombre:'Espinaca 100g',cal:23,prot:2.9,carb:3.6,grasa:0.4,emoji:'🥬',cat:'Verdura'},
{id:24,nombre:'Aceite oliva 1 cda',cal:119,prot:0,carb:0,grasa:13.5,emoji:'🫒',cat:'Grasa saludable'},
{id:25,nombre:'Miel 1 cda',cal:64,prot:0,carb:17,grasa:0,emoji:'🍯',cat:'Carbohidrato'},
{id:26,nombre:'Crema cacahuate 20g',cal:118,prot:5,carb:4,grasa:10,emoji:'🥜',cat:'Grasa saludable'},
{id:27,nombre:'Tilapia 100g',cal:96,prot:20,carb:0,grasa:1.7,emoji:'🐟',cat:'Proteína'},
{id:28,nombre:'Camote 100g',cal:86,prot:1.6,carb:20,grasa:0.1,emoji:'🍠',cat:'Carbohidrato'},
{id:29,nombre:'Fresa 100g',cal:32,prot:0.7,carb:8,grasa:0.3,emoji:'🍓',cat:'Fruta'},
{id:30,nombre:'Clara huevo 3 pzas',cal:51,prot:11,carb:0.7,grasa:0.2,emoji:'🥚',cat:'Proteína'},
{id:31,nombre:'Camarón 100g',cal:99,prot:24,carb:0.2,grasa:0.3,emoji:'🦐',cat:'Proteína'},
{id:32,nombre:'Lentejas 100g cocidas',cal:116,prot:9,carb:20,grasa:0.4,emoji:'🍲',cat:'Carbohidrato'},
{id:33,nombre:'Pepino 100g',cal:16,prot:0.7,carb:3.6,grasa:0.1,emoji:'🥒',cat:'Verdura'},
{id:34,nombre:'Zanahoria 100g',cal:41,prot:0.9,carb:10,grasa:0.2,emoji:'🥕',cat:'Verdura'},
{id:35,nombre:'Arándanos 100g',cal:57,prot:0.7,carb:14,grasa:0.3,emoji:'🫐',cat:'Fruta'},
{id:36,nombre:'Quinoa cocida 100g',cal:120,prot:4.4,carb:22,grasa:1.9,emoji:'🌾',cat:'Carbohidrato'},
{id:37,nombre:'Hummus 50g',cal:166,prot:8,carb:14,grasa:10,emoji:'🧆',cat:'Grasa saludable'},
{id:38,nombre:'Jugo naranja 250ml',cal:112,prot:1.7,carb:26,grasa:0.5,emoji:'🍊',cat:'Fruta'},
{id:39,nombre:'Granola 40g',cal:187,prot:5,carb:26,grasa:7,emoji:'🥣',cat:'Carbohidrato'},
{id:40,nombre:'Chocolate oscuro 20g',cal:110,prot:1.5,carb:9,grasa:8,emoji:'🍫',cat:'Grasa saludable'},
];

export const RUTINAS_DB=[
{id:'e1',nombre:'Sentadilla',categoria:'Piernas',met:6,emoji:'🦵',dif:'Intermedio',desc:'4x12, 90s descanso'},
{id:'e2',nombre:'Press banca',categoria:'Pecho',met:5,emoji:'🏋️',dif:'Intermedio',desc:'4x10, 90s descanso'},
{id:'e3',nombre:'Dominadas',categoria:'Espalda',met:7,emoji:'💪',dif:'Avanzado',desc:'4x8, 120s descanso'},
{id:'e4',nombre:'Plancha',categoria:'Core',met:4,emoji:'🧱',dif:'Principiante',desc:'3x60s, 60s descanso'},
{id:'e5',nombre:'Burpees',categoria:'Cardio',met:8,emoji:'🔥',dif:'Avanzado',desc:'4x15, 60s descanso'},
{id:'e6',nombre:'Peso muerto',categoria:'Piernas',met:6,emoji:'🏋️',dif:'Avanzado',desc:'4x8, 120s descanso'},
{id:'e7',nombre:'Flexiones',categoria:'Pecho',met:5,emoji:'💥',dif:'Principiante',desc:'3x15, 60s descanso'},
{id:'e8',nombre:'Zancadas',categoria:'Piernas',met:5,emoji:'🦵',dif:'Intermedio',desc:'3x12 por pierna'},
{id:'e9',nombre:'Remo con barra',categoria:'Espalda',met:6,emoji:'🚣',dif:'Intermedio',desc:'4x10'},
{id:'e10',nombre:'Press militar',categoria:'Hombros',met:5,emoji:'🏋️',dif:'Intermedio',desc:'4x10'},
{id:'e11',nombre:'Curl bíceps',categoria:'Brazos',met:4,emoji:'💪',dif:'Principiante',desc:'3x12'},
{id:'e12',nombre:'Fondos',categoria:'Pecho',met:6,emoji:'🔥',dif:'Avanzado',desc:'3x12'},
{id:'e13',nombre:'Ab wheel',categoria:'Core',met:6,emoji:'🎡',dif:'Avanzado',desc:'3x12'},
{id:'e14',nombre:'Jumping jacks',categoria:'Cardio',met:7,emoji:'🤸',dif:'Principiante',desc:'4x30s'},
{id:'e15',nombre:'Hip thrust',categoria:'Piernas',met:5,emoji:'🍑',dif:'Intermedio',desc:'4x12'},
{id:'e16',nombre:'Pull over',categoria:'Pecho',met:4,emoji:'🧘',dif:'Intermedio',desc:'3x12'},
{id:'e17',nombre:'Plancha lateral',categoria:'Core',met:4,emoji:'🧱',dif:'Intermedio',desc:'3x45s por lado'},
{id:'e18',nombre:'Mountain climbers',categoria:'Cardio',met:8,emoji:'⛰️',dif:'Intermedio',desc:'4x30s'},
{id:'e19',nombre:'Press inclinado',categoria:'Pecho',met:5,emoji:'🏋️',dif:'Intermedio',desc:'4x10'},
{id:'e20',nombre:'Peso muerto rumano',categoria:'Piernas',met:5,emoji:'🦵',dif:'Intermedio',desc:'4x10'},
{id:'e21',nombre:'Face pull',categoria:'Hombros',met:4,emoji:'🎯',dif:'Principiante',desc:'3x15'},
{id:'e22',nombre:'Extensión tríceps',categoria:'Brazos',met:4,emoji:'💪',dif:'Principiante',desc:'3x12'},
{id:'e23',nombre:'Sprints',categoria:'Cardio',met:10,emoji:'🏃',dif:'Avanzado',desc:'6x30m'},
{id:'e24',nombre:'Pallof press',categoria:'Core',met:4,emoji:'🧱',dif:'Intermedio',desc:'3x12 por lado'},
{id:'e25',nombre:'Sentadilla búlgara',categoria:'Piernas',met:6,emoji:'🦵',dif:'Avanzado',desc:'3x10 por pierna'},
];

export const LOGROS=[
{id:'primer', n:'Primer Paso', d:'Primera comida', icon:'🌱', tipo:'comidas', req:1, xp:10},
{id:'llamas', n:'Racha 3', d:'3 días seguidos', icon:'🔥', tipo:'racha', req:3, xp:50},
{id:'const', n:'Constancia', d:'5 rutinas', icon:'💪', tipo:'rutinas', req:5, xp:75},
{id:'nutri', n:'Nutrición', d:'20 alimentos', icon:'🍎', tipo:'comidas', req:20, xp:75},
{id:'puntual', n:'Puntual', d:'7 días', icon:'⏰', tipo:'racha', req:7, xp:100},
{id:'nivel5', n:'Nivel 5', d:'Alcanza nivel 5', icon:'🏆', tipo:'nivel', req:5, xp:200},
{id:'leyenda', n:'Leyenda', d:'30 días', icon:'👑', tipo:'racha', req:30, xp:500},
{id:'perf', n:'Enfoque', d:'10 objetivos', icon:'🎯', tipo:'objetivo', req:10, xp:150},
{id:'chef', n:'Chef', d:'50 alimentos', icon:'👨‍🍳', tipo:'comidas', req:50, xp:150},
{id:'atleta', n:'Atleta', d:'20 rutinas', icon:'🏅', tipo:'rutinas', req:20, xp:200},
];
